### ISSUE TITLE
P̶r̶o̶g̶r̶e̶s̶s̶i̶v̶e̶ ̶W̶e̶b̶ ̶A̶p̶p̶ / Play Store Webview app

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/Proost#28]
Het is waarschijnlijk wel een leuk idee om de site ook om te bouwen tot PWA.
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps

Ook zal een play store app goed zijn voor publicity. Een app met een webview zal prima zijn. Misschien ook leuk om URLs van https://proost.app/ via de app te openen.

**Comment by MarvinHoffenkamp** [comment]
Zie #35 voor PWA  #support.

**Comment by Naamloos** [comment]
#35 geeft prima support voor PWAs. Denk niet per se dat een android app extra waarde toevoegt. Er zijn genoeg sites die zonder app prima werken. Closed.
