### ISSUE TITLE
Reconsider naming

### ISSUE THREAD

**Issue by Naamloos** [Naamloos/Proost#53]
Apparently someone already made THE EXACT SAME THING WITH THE EXACT SAME NAME...

Might name it "proostapp" because I already bought the domain for 2 years.

**Comment by Naamloos** [comment]
https://play.google.com/store/apps/details?id=nl.joepVerhoeven.Picollo

**Comment by JesperKuipers** [comment]
ProostApp has my vote

**Comment by Naamloos** [comment]
ProostApp it is. Already changed never closed.
